#!/bin/sh

# cd to file containing script or something?
BASEDIR=$(dirname "$0")
echo "$BASEDIR"
cd "$BASEDIR"

mkdir -p "$HOME/Library/Application Support/Trauma Station"

ARCH=$(uname -m)

export DOTNET_ROOT="$(pwd)/../Resources/$ARCH/dotnet"

# Why do we invoke dotnet with the dll, instead of the apphost?
# Because for some reason, the ARM64 apphost is broken when published by GitHub Actions.
# Idk dude. This works.
exec "$DOTNET_ROOT/dotnet" ../Resources/$ARCH/bin/Trauma.Launcher.dll "$@" > "$HOME/Library/Application Support/Trauma Station/launcher.log"
